### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by VictorOmondiCDS** [IVYMWAI/Data-Cleaning#1]
This project looks amazing @IVYMWAI, Great job in doing data cleaning. Here's my review:
1. **Project Overview**: Provide the project goal and overview so that others can know what the project is about, which data you are working on, and the end goal you are trying to achieve. Do the same to the README.md file
2. **Installation**: Provide a clear step-by-step method to be followed by other analysts if they have to replicate the exact steps you followed. Add a `requirements.txt` file with the versions of the library used and instructions on creating a virtual environment and activating it
3. **Storytelling**: The good thing about a data project is the story, moving readers step by step on what you are doing and why, and also providing further info on the outcome. For your notebook, we would expect more information about what you are doing and the outcome of the processes
4. **Content management**: Organize your files nicely, and have a directory where your data is stored (maybe call it `data`). The notebooks can be in the `notebooks` directory or in the root folder as you've done:
```sh
Project/
├── data/
│   ├── Clean Airbnb_data.xlsx
│   ├── Open Airbnb Data.csv
│   ├── Open Airbnb Data.xlsx
├── Data cleaning.ipynb
└── README.md
```

**Comment by IVYMWAI** [comment]
Hello Victor,
Thank you for your honest review,I am glad you love my project.
However,I have a question,where do I write this project overview?Isn't the
Readme supposed to contain all these steps?

Kind regards
Ivy Mwai

**Comment by VictorOmondiCDS** [comment]
README.md should contain info about the project, and installation instructions
your Jupyter Notebook file should contain the storytelling bit, explaining every aspect you are doing

**Comment by IVYMWAI** [comment]
Thank you for the tip,but,Victor,kindly send me one of your project's links
so I can have an idea on how to go about it?
Regards
Ivy Mwai.
